---
site:
  lang: hu
  locale: hu_HU
  name: &siteName Ábrás Cet
  author: Bata Gábor
  domain: https://www.abras-cet.hu
navigation:
  home: *siteName
  images: Képek
  archive: Archív
  about: A cetről
